#####################################################
#
#   PORTFOLIO WEBSITE CI/CD PIPELINE
#
#

stages:
    - development   #Pushes code to development site.
    - production    #Pushes code to production site.

# #### DEVELOPMENT ####
deploy-to-development-server:
        stage: development
        tags:
            - cp2 #Only runner with this tag will run this pipeline
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
                - "*.md" #Ignore .md files
                - Screenshot.png
        only:
            refs:
                - branches #Changes to branches trigger pipeline
        script:
            - if [ -z "$portfolio_development_webroot" ]; then echo "Need to set webroot" && exit 1; fi
            - sudo rsync -avzr ./ $portfolio_development_webroot ---exclude-from='./_exclusions.txt' --delete
            - sudo chown admin:admin $portfolio_development_webroot -R

#### PRODUCTION ####
deploy-to-production-server:
        environment:
            name: production
        stage: production
        tags:
            - cp2 #Only runner with this tag will run this pipeline
        except:
            changes: #Ignore changes to the following files
                - _exclusings.txt
                - .* #Ignore dot files
                - "*.md" #Ignore .md files
                - Screenshot.png
        only: 
            refs:
                - branches #Changes to branches trigger pipeline
        when: manual #Runner will only run with manual intervention
        script:
            - if [ -z "$portfolio_production_webroot" ]; then echo "Need to set webroot" && exit 1; fi
            - sudo rsync -avzr ./ $portfolio_production_webroot --exclude-from='./_exclusions.txt' --delete
            - sudo chown admin:admin $portfolio_production_webroot -R